### ISSUE TITLE
Feature request - Add Agency and Division

### ISSUE THREAD

**Issue by brunns** [jimstorch/DGGen#4]
@jimstorch How would you feel about picking an agency and division for each character, then basing the profession off that? 

We could also select from the bonus skills for that division, and least most of the time, giving more focused characters.

Happy to make the changes if you think it's an idea with legs.

**Comment by jimstorch** [comment]
Hey Simon,

I like it.  One thing on my wishlist is a kind of mini-greenbox for each
profession.  So an Agent would get a random firearm and maybe cuffs, a
scientist might have a laptop and Geiger-counter.  Basic gearing to make
each character more "batteries-included."

-Jim

**Comment by arnoid** [comment]
@jimstorch have you made contact with Arc Dream Publishing? Cos' agencies are not available in "Need To Know". Agencies are described in "Agent handbook" which is paid and not available as open source.

Do they give permission to use handbooks descriptions?

Otherwise generation of agents based on non-disclosed information can be illegal.

**Comment by jimstorch** [comment]
@arnoid OP is from over a year ago.  Nothing has been pursued.  I will say that Dennis Detwiler and Simeon Cogswell from Arc Dream have been supportive and incredibly generous.  I would delete the project rather than offend them.

Just FYI, 'Need to Know' is not 'open source'.  It is copyright 2016, Shane Ivey and Bret Kramer.  The Open Game License on page 4 does not grant any rights to 'Need to Know'.  It's them asserting _their_ rights to use OGL content from Mongoose Publishing's 'Legend'.

**Comment by arnoid** [comment]
@jimstorch, I had no intent to offend your brilliant creation. I was just wondering.
Thnx, for information regarding the 'Need to know'.

P.S. I am also interested in Arc Dream Pub. reaction, cos' right now I am trying to build android app with agent generator and export to google sheets for following modification and printing.

**Comment by jimstorch** [comment]
Ask them.  They're nice guys who are trying to grow a brand.

**Comment by arnoid** [comment]
Cool thnx

**Comment by brunns** [comment]
We could probably do the agency & division thing with alternate `professions.json`files now. Perhaps we'd like CLI options to pick a different file, and to throw together a few example agency specific files?

**Comment by brunns** [comment]
I think this can be closed now?
